#version: "3.8"
version: "3.7"
services:


  postgres:
    image: postgres
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

